### ISSUE TITLE
Enhancements for SHAWI

### ISSUE THREAD

**Issue by simar0at** [acdh-oeaw/vicav-app#56]
For the SHAW I project the platform needs to be extended to provide 

- [x] #54
   - [x]  https://github.com/acdh-oeaw/shawi-data/issues/8
- [x]  #57
- [x] #55
  - [x] #59
  - [x]  https://github.com/acdh-oeaw/shawi-data/issues/10
  - [x] #60
    - [x] https://github.com/acdh-oeaw/vicav-vue3/issues/31
    - [x] https://github.com/acdh-oeaw/vicav-vue3/issues/32
    - [x] https://github.com/acdh-oeaw/vicav-vue3/issues/33
